/**
 * `zetaplugin.toml` — the file a plugin author actually writes — and its
 * translation into the `manifest.json` that goes inside the package.
 *
 * Metadata is data, not code. Keeping it in TOML means it can be validated with
 * a sentence a human understands, diffed, and generated by a script; the same
 * information expressed as a Gradle DSL can only fail as a Kotlin compile error.
 */
import fs from "node:fs";
import path from "node:path";
import { parse as parseToml } from "smol-toml";
import { ZetaError } from "../errors.js";
import { HOST_API_VERSION, MANIFEST_FORMAT_VERSION, UI_API_VERSION, PROJECT } from "../config.js";

const SETTING_TYPES = [
  "switch", "number", "decimal", "text", "choice", "multiChoice", "folder", "action",
];

const SPECIAL_ACCESS = [
  "allFilesAccess", "displayOverOtherApps", "exactAlarms", "usageAccess",
  "notificationAccess", "ignoreBatteryOptimizations", "installPackages", "writeSettings",
];

const ID_PATTERN = /^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)+$/;
const VERSION_PATTERN = /^\d+\.\d+\.\d+(-[0-9A-Za-z.-]+)?$/;

/** Finds the project root by walking up from `start` looking for the TOML. */
export function findProjectRoot(start = process.cwd()) {
  let dir = path.resolve(start);
  for (;;) {
    if (fs.existsSync(path.join(dir, PROJECT.manifestFile))) return dir;
    const parent = path.dirname(dir);
    if (parent === dir) return null;
    dir = parent;
  }
}

/** Loads and validates the project descriptor. */
export function loadProject(start) {
  const root = findProjectRoot(start);
  if (!root) {
    throw new ZetaError(`No ${PROJECT.manifestFile} found here or in any parent folder.`, {
      hint: "Create a plugin with:  zeta new my-plugin",
      docs: "plugin-anatomy.md",
    });
  }

  const file = path.join(root, PROJECT.manifestFile);
  let raw;
  try {
    raw = parseToml(fs.readFileSync(file, "utf8"));
  } catch (error) {
    throw new ZetaError(`${PROJECT.manifestFile} is not valid TOML.`, {
      where: file,
      detail: error.message,
      hint: "Check quotes and brackets around the line mentioned above.",
      docs: "plugin-anatomy.md",
    });
  }

  return { root, file, ...validate(raw, file) };
}

function required(section, key, value, file, hint) {
  if (value === undefined || value === null || value === "") {
    throw new ZetaError(`[${section}] is missing "${key}".`, {
      where: file,
      hint,
      docs: "plugin-anatomy.md",
    });
  }
  return value;
}

function validate(raw, file) {
  const plugin = raw.plugin || {};

  const id = required("plugin", "id", plugin.id, file, 'For example:  id = "com.example.myplugin"');
  if (!ID_PATTERN.test(id)) {
    throw new ZetaError(`"${id}" is not a valid plugin id.`, {
      where: file,
      hint: "Use reverse-DNS in lowercase, at least two parts:  com.example.myplugin",
      docs: "plugin-anatomy.md",
    });
  }

  const version = required("plugin", "version", plugin.version, file, 'For example:  version = "1.0.0"');
  if (!VERSION_PATTERN.test(version)) {
    throw new ZetaError(`"${version}" is not a valid version.`, {
      where: file,
      hint: "Use major.minor.patch, for example 1.0.0 — the Host sorts updates by it.",
    });
  }

  const entryPoint = required(
    "plugin", "entryPoint", plugin.entryPoint, file,
    'The fully qualified class implementing ZetaPlugin, e.g. "com.example.myplugin.MyPlugin"',
  );

  const minHostApi = plugin.minHostApi ?? HOST_API_VERSION;
  const maxHostApi = plugin.maxHostApi ?? Math.max(minHostApi, HOST_API_VERSION);

  // Checked before the min/max sanity rule: "install a newer CLI" is far more
  // useful than "min is greater than max" when the author asked for a future API.
  if (minHostApi > HOST_API_VERSION) {
    throw new ZetaError(
      `This plugin requires Host API ${minHostApi}, but this CLI builds for Host API ${HOST_API_VERSION}.`,
      {
        where: file,
        hint: `Install a newer CLI:  npm install -g zetaforge@${minHostApi}`,
        docs: "versioning.md",
      },
    );
  }

  if (minHostApi > maxHostApi) {
    throw new ZetaError(`minHostApi (${minHostApi}) is greater than maxHostApi (${maxHostApi}).`, {
      where: file,
      hint: "minHostApi is what you require; maxHostApi is what you have tested.",
      docs: "versioning.md",
    });
  }

  const permissions = (raw.permission || []).map((p, index) => {
    if (!p.name) {
      throw new ZetaError(`[[permission]] #${index + 1} has no "name".`, {
        where: file,
        hint: 'For example:  name = "android.permission.INTERNET"',
        docs: "permissions.md",
      });
    }
    if (!p.reason) {
      throw new ZetaError(`Permission "${p.name}" has no "reason".`, {
        where: file,
        hint: "The reason is shown to the user when the Host asks for the permission. Write it for them, not for you.",
        docs: "permissions.md",
      });
    }
    return {
      name: p.name,
      reason: p.reason,
      optional: p.optional === true,
      minSdk: p.minSdk ?? 1,
      maxSdk: p.maxSdk ?? 2147483647,
    };
  });

  const specialAccess = (raw.specialAccess || []).map((s, index) => {
    const sid = s.id || s.name;
    if (!sid) {
      throw new ZetaError(`[[specialAccess]] #${index + 1} has no "id".`, {
        where: file,
        hint: `One of: ${SPECIAL_ACCESS.join(", ")}`,
        docs: "permissions.md",
      });
    }
    if (!SPECIAL_ACCESS.includes(sid)) {
      throw new ZetaError(`"${sid}" is not a known special access.`, {
        where: file,
        hint: `Valid values: ${SPECIAL_ACCESS.join(", ")}`,
        docs: "permissions.md",
      });
    }
    return { id: sid, reason: s.reason || "", optional: s.optional === true };
  });

  const seenKeys = new Set();
  const settings = (raw.setting || []).map((s, index) => {
    if (!s.key) {
      throw new ZetaError(`[[setting]] #${index + 1} has no "key".`, {
        where: file, docs: "settings.md",
      });
    }
    if (seenKeys.has(s.key)) {
      throw new ZetaError(`Two settings share the key "${s.key}".`, {
        where: file,
        hint: "The key is how the value reaches your code, so it has to be unique.",
        docs: "settings.md",
      });
    }
    seenKeys.add(s.key);
    if (!SETTING_TYPES.includes(s.type)) {
      throw new ZetaError(`Setting "${s.key}" has an unknown type "${s.type}".`, {
        where: file,
        hint: `Valid types: ${SETTING_TYPES.join(", ")}`,
        docs: "settings.md",
      });
    }
    if ((s.type === "choice" || s.type === "multiChoice") && !(s.options || []).length) {
      throw new ZetaError(`Setting "${s.key}" is a ${s.type} but has no options.`, {
        where: file,
        hint: 'For example:  options = ["hevc", "avc"]',
        docs: "settings.md",
      });
    }
    const entry = {
      type: s.type,
      key: s.key,
      label: s.label || s.key,
      description: s.description || "",
      group: s.group || "",
      advanced: s.advanced === true,
      default: s.default ?? defaultFor(s.type),
    };
    if (s.min !== undefined) entry.min = s.min;
    if (s.max !== undefined) entry.max = s.max;
    if (s.step !== undefined) entry.step = s.step;
    if (s.unit) entry.unit = s.unit;
    if (s.hint) entry.hint = s.hint;
    if (s.secret) entry.secret = true;
    if (s.options) {
      entry.options = s.options;
      entry.optionLabels = s.optionLabels || s.options;
    }
    if (s.runningLabel) entry.runningLabel = s.runningLabel;
    return entry;
  });

  const dependencies = Object.entries(raw.dependencies || {}).map(([name, value]) => {
    const coordinate = typeof value === "string" ? value : value.module;
    if (!coordinate || coordinate.split(":").length < 3) {
      throw new ZetaError(`Dependency "${name}" is not a valid Maven coordinate.`, {
        where: file,
        hint: 'Use group:artifact:version, for example  retrofit = "com.squareup.retrofit2:retrofit:2.11.0"',
        docs: "dependencies.md",
      });
    }
    return { name, coordinate, excludeKotlin: value.excludeKotlin !== false };
  });

  // A screen is declared, never detected: the Host reads this before loading
  // any of the plugin's code, which is what lets it show (or refuse) OPEN
  // without running a single line of it.
  const ui = raw.ui
    ? {
        enabled: raw.ui.enabled !== false,
        uiApi: raw.ui.uiApi ?? UI_API_VERSION,
        only: raw.ui.only === true,
        label: raw.ui.label || "",
      }
    : null;

  if (ui && ui.uiApi > UI_API_VERSION) {
    throw new ZetaError(
      `This plugin targets screen contract ${ui.uiApi}, but this CLI builds for ${UI_API_VERSION}.`,
      {
        where: file,
        hint: "Install a newer CLI, or lower uiApi in the [ui] block.",
        docs: "versioning.md",
      },
    );
  }

  return {
    plugin: {
      id,
      name: plugin.name || id.split(".").pop(),
      version,
      description: plugin.description || "",
      author: plugin.author || "",
      homepage: plugin.homepage || "",
      license: plugin.license || "",
      entryPoint,
      minHostApi,
      maxHostApi,
      minSdk: plugin.minSdk ?? 26,
      category: plugin.category || "",
    },
    permissions,
    specialAccess,
    settings,
    dependencies,
    // "ui" is added for the plugin, so the declaration and the capability
    // list can never disagree.
    capabilities: withUiCapability(raw.plugin?.capabilities || [], ui),
    ui,
  };
}

function withUiCapability(capabilities, ui) {
  if (!ui || !ui.enabled || capabilities.includes("ui")) return capabilities;
  return [...capabilities, "ui"];
}

function defaultFor(type) {
  switch (type) {
    case "switch": return false;
    case "number": return 0;
    case "decimal": return 0.0;
    case "multiChoice": return [];
    case "action": return null;
    default: return "";
  }
}

/**
 * Builds the manifest.json that goes into the package.
 * @param {object} project the loaded project
 * @param {object} code the `code` block, filled in after dexing
 */
export function buildManifest(project, code) {
  return {
    formatVersion: MANIFEST_FORMAT_VERSION,
    pluginId: project.plugin.id,
    name: project.plugin.name,
    version: project.plugin.version,
    description: project.plugin.description,
    author: project.plugin.author,
    homepage: project.plugin.homepage,
    license: project.plugin.license,
    entryPoint: project.plugin.entryPoint,
    minHostApi: project.plugin.minHostApi,
    maxHostApi: project.plugin.maxHostApi,
    minSdk: project.plugin.minSdk,
    permissions: project.permissions,
    specialAccess: project.specialAccess,
    capabilities: project.capabilities,
    settings: project.settings,
    ...(project.ui && project.ui.enabled
      ? {
          ui: {
            enabled: true,
            uiApi: project.ui.uiApi,
            only: project.ui.only,
            ...(project.ui.label ? { label: project.ui.label } : {}),
          },
        }
      : {}),
    dependencies: {
      bundled: project.dependencies.map((d) => d.coordinate),
      hostProvided: [
        `com.zetaforge:plugin-api:${HOST_API_VERSION}`,
        "org.jetbrains.kotlin:kotlin-stdlib",
        "org.jetbrains.kotlinx:kotlinx-coroutines-core",
      ],
    },
    code,
    signature: null,
    display: { category: project.plugin.category, icon: "" },
    builtBy: `zeta-cli`,
  };
}
