/**
 * Turning a plugin project into `classes.dex`.
 *
 * The chain is deliberately short: Kotlin/JVM → d8 → done. No Android Gradle
 * Plugin, because a plugin has no resources, no manifest to merge and no APK to
 * produce — AGP would only contribute the slow half of a build we do not need.
 *
 * Gradle is still here, but only for what it is genuinely good at: resolving
 * Maven dependencies and running the Kotlin compiler. The developer never sees
 * it and never edits a build file: it is generated into `.zeta/` from the
 * project descriptor.
 */
import fs from "node:fs";
import path from "node:path";
import { spawn } from "node:child_process";
import { ZetaError } from "../errors.js";
import { paths, PROJECT } from "../config.js";
import { findJava } from "../env/java.js";
import { findAndroidJar } from "../env/android.js";

export const KOTLIN_VERSION = "2.1.20";
export const COROUTINES_VERSION = "1.10.2";
export const R8_VERSION = "8.9.35";

/**
 * The Compose bill of materials the Host ships, and therefore the only one a
 * screen plugin may compile against.
 *
 * It has to match the Host's: Compose is a boundary type, so the plugin's
 * composable and the Host's composition have to agree on the same class
 * objects. Compiling against a newer Compose than the Host provides is how you
 * get a NoSuchMethodError on the first frame instead of a screen.
 */
export const COMPOSE_BOM = "2025.04.01";

/** Writes the generated Gradle build. Idempotent: safe to call every build. */
export function prepareWorkspace(project, options = {}) {
  const work = path.join(project.root, PROJECT.workDir);
  fs.mkdirSync(path.join(work, "gradle", "wrapper"), { recursive: true });

  const androidJar = options.androidJar || findAndroidJar().jar;

  for (const name of ["gradlew", "gradlew.bat"]) {
    const target = path.join(work, name);
    fs.copyFileSync(path.join(paths.gradleRecipe, name), target);
    if (name === "gradlew") fs.chmodSync(target, 0o755);
  }
  for (const name of ["gradle-wrapper.jar", "gradle-wrapper.properties"]) {
    fs.copyFileSync(
      path.join(paths.gradleRecipe, "wrapper", name),
      path.join(work, "gradle", "wrapper", name),
    );
  }

  fs.writeFileSync(
    path.join(work, "settings.gradle.kts"),
    [
      "// Generated by the zeta CLI. Edits are overwritten on every build.",
      "dependencyResolutionManagement {",
      "    repositories { google(); mavenCentral() }",
      "}",
      `rootProject.name = ${JSON.stringify(project.plugin.id.split(".").pop())}`,
      "",
    ].join("\n"),
  );

  fs.writeFileSync(
    path.join(work, "gradle.properties"),
    [
      "org.gradle.jvmargs=-Xmx2g",
      "org.gradle.daemon=true",
      "org.gradle.parallel=true",
      "org.gradle.caching=true",
      "kotlin.incremental=true",
      "",
    ].join("\n"),
  );

  fs.writeFileSync(path.join(work, "build.gradle.kts"), buildScript(project, androidJar));
  fs.writeFileSync(path.join(work, ".gitignore"), "*\n");
  return { work, androidJar };
}

function buildScript(project, androidJar) {
  const q = (value) => JSON.stringify(String(value).replace(/\\/g, "/"));

  // A plugin with a [ui] block is compiled with the Compose compiler and
  // against the Host's Compose - all of it compileOnly, exactly like the
  // contract and the Kotlin runtime. None of it reaches the plugin's DEX.
  const hasUi = Boolean(project.ui && project.ui.enabled);

  const bundled = project.dependencies
    .map((d) =>
      d.excludeKotlin
        ? `    bundled(${q(d.coordinate)}) { exclude(group = "org.jetbrains.kotlin") }`
        : `    bundled(${q(d.coordinate)})`,
    )
    .join("\n");

  return `// Generated by the zeta CLI from ${PROJECT.manifestFile}. Do not edit.
plugins {
    id("org.jetbrains.kotlin.jvm") version "${KOTLIN_VERSION}"
${hasUi ? `    id("org.jetbrains.kotlin.plugin.compose") version "${KOTLIN_VERSION}"` : ""}
}

val androidJar = ${q(androidJar)}
val contractJar = ${q(paths.contractJar)}

// Everything the plugin carries in its own DEX.
val bundled: Configuration by configurations.creating
val d8tool: Configuration by configurations.creating
${hasUi ? "// Compiled against, never packaged: the Host owns every one of these.\nval hostProvided: Configuration by configurations.creating" : ""}

dependencies {
    // Provided by the Host at run time. Compiling against them is required;
    // bundling them would break the boundary, because the same class has to
    // resolve to the same object on both sides.
    compileOnly(files(androidJar))
    compileOnly(files(contractJar))
    compileOnly("org.jetbrains.kotlin:kotlin-stdlib:${KOTLIN_VERSION}")
    compileOnly("org.jetbrains.kotlinx:kotlinx-coroutines-core:${COROUTINES_VERSION}")

${bundled || "    // (no external dependencies declared)"}

    d8tool("com.android.tools:r8:${R8_VERSION}")
${hasUi ? `    hostProvided(platform("androidx.compose:compose-bom:${COMPOSE_BOM}"))
    hostProvided("androidx.compose.runtime:runtime")
    hostProvided("androidx.compose.ui:ui")
    hostProvided("androidx.compose.ui:ui-graphics")
    hostProvided("androidx.compose.foundation:foundation")
    hostProvided("androidx.compose.material3:material3")` : ""}

    testImplementation(files(androidJar))
    testImplementation(files(contractJar))
    testImplementation("org.jetbrains.kotlin:kotlin-stdlib:${KOTLIN_VERSION}")
    testImplementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:${COROUTINES_VERSION}")
    testImplementation("org.jetbrains.kotlin:kotlin-test:${KOTLIN_VERSION}")
    testImplementation("org.jetbrains.kotlinx:kotlinx-coroutines-test:${COROUTINES_VERSION}")
}

sourceSets {
    named("main") { kotlin.setSrcDirs(listOf("../${PROJECT.sourceDir}")) }
    named("test") { kotlin.setSrcDirs(listOf("../${PROJECT.testDir}")) }
}

kotlin { compilerOptions { jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17) } }
java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}
tasks.withType<Test> { useJUnitPlatform() }

// An Android library ships as an .aar, a zip whose classes live in classes.jar.
// A plain Kotlin/JVM build cannot consume one, so unwrap it here.
val unwrapDependencies by tasks.registering {
    val out = layout.buildDirectory.dir("bundled")
    outputs.dir(out)
    doLast {
        val dir = out.get().asFile.apply { deleteRecursively(); mkdirs() }
        bundled.resolvedConfiguration.resolvedArtifacts.forEach { artifact ->
            if (artifact.file.extension == "aar") {
                copy {
                    from(zipTree(artifact.file)) { include("classes.jar") }
                    into(dir)
                    rename { artifact.name + ".jar" }
                }
            } else {
                copy { from(artifact.file); into(dir) }
            }
        }
    }
}

${hasUi ? `
// The Host's Compose arrives as .aar files, which a plain Kotlin/JVM build
// cannot read. Unwrapped here into the classes.jar each one contains, and put
// on the compile classpath only - never on the d8 inputs below, which is what
// keeps Compose out of the plugin's DEX.
val unwrapHostProvided by tasks.registering {
    val out = layout.buildDirectory.dir("hostProvided")
    outputs.dir(out)
    doLast {
        val dir = out.get().asFile.apply { deleteRecursively(); mkdirs() }
        hostProvided.resolvedConfiguration.resolvedArtifacts.forEachIndexed { index, artifact ->
            if (artifact.file.extension == "aar") {
                copy {
                    from(zipTree(artifact.file)) { include("classes.jar") }
                    into(dir)
                    rename { index.toString() + "-" + artifact.name + ".jar" }
                }
            } else {
                copy { from(artifact.file); into(dir) }
            }
        }
    }
}
` : ""}
dependencies {
    compileOnly(fileTree(layout.buildDirectory.dir("bundled")) { include("*.jar") })
    testImplementation(fileTree(layout.buildDirectory.dir("bundled")) { include("*.jar") })
${hasUi ? `    compileOnly(fileTree(layout.buildDirectory.dir("hostProvided")) { include("*.jar") })
    testImplementation(fileTree(layout.buildDirectory.dir("hostProvided")) { include("*.jar") })` : ""}
}
tasks.named("compileKotlin") { dependsOn(unwrapDependencies${hasUi ? ", unwrapHostProvided" : ""}) }
tasks.named("compileTestKotlin") { dependsOn(unwrapDependencies${hasUi ? ", unwrapHostProvided" : ""}) }

// --- dexing ---------------------------------------------------------------

val zetaDex by tasks.registering(JavaExec::class) {
    group = "zetaforge"
    dependsOn(tasks.named("jar"), unwrapDependencies)
    mainClass.set("com.android.tools.r8.D8")
    classpath = d8tool

    val outputDir = layout.buildDirectory.dir("dex")
    val pluginJar = tasks.named<Jar>("jar").flatMap { it.archiveFile }
    val bundledDir = layout.buildDirectory.dir("bundled")

    inputs.file(pluginJar)
    inputs.dir(bundledDir)
    outputs.dir(outputDir)

    doFirst {
        val dir = outputDir.get().asFile.apply { deleteRecursively(); mkdirs() }
        val inputs = mutableListOf(pluginJar.get().asFile.absolutePath)
        bundledDir.get().asFile.listFiles { f -> f.extension == "jar" }?.forEach {
            inputs += it.absolutePath
        }
        args = listOf(
            "--release",
            "--min-api", "${project.plugin.minSdk}",
            "--lib", androidJar,
            "--output", dir.absolutePath,
        ) + inputs
    }
}
`;
}

/**
 * Runs a Gradle task in the generated workspace.
 * @returns {Promise<{output:string, ms:number}>}
 */
export function runGradle(work, tasks, options = {}) {
  const java = findJava();
  const wrapper = process.platform === "win32"
    ? path.join(work, "gradlew.bat")
    : path.join(work, "gradlew");

  const args = [...tasks, "--console=plain"];
  if (!options.verbose) args.push("-q");
  if (options.offline) args.push("--offline");

  const started = Date.now();
  return new Promise((resolve, reject) => {
    const child = spawn(wrapper, args, {
      cwd: work,
      env: { ...process.env, JAVA_HOME: java.home },
      shell: process.platform === "win32",
    });

    let output = "";
    const collect = (chunk) => {
      output += chunk;
      if (options.verbose) process.stdout.write(chunk);
    };
    child.stdout.on("data", collect);
    child.stderr.on("data", collect);

    child.on("error", (error) =>
      reject(new ZetaError(`Could not start Gradle: ${error.message}`, {
        hint: "Check that the CLI was installed completely (try reinstalling zetaforge-cli).",
      })),
    );

    child.on("close", (code) => {
      if (code === 0) return resolve({ output, ms: Date.now() - started });
      reject(compileError(output));
    });
  });
}

/**
 * Turns Gradle noise into the one thing that went wrong.
 *
 * Kotlin reports errors as `e: file:///path/File.kt:12:5 message`, which is
 * precise but buried in eighty lines of Gradle ceremony.
 */
function compileError(output) {
  const kotlinErrors = [...output.matchAll(/^e: file:\/\/\/(.+?):(\d+):(\d+) (.+)$/gm)];

  if (kotlinErrors.length > 0) {
    const [, file, line, column, message] = kotlinErrors[0];
    const readable = path.relative(process.cwd(), file.replace(/^\/?([A-Za-z]):/, "$1:"));
    const more = kotlinErrors.length > 1 ? ` (and ${kotlinErrors.length - 1} more)` : "";
    return new ZetaError(`${message}${more}`, {
      where: `${readable}:${line}:${column}`,
      hint: kotlinErrors.length > 1
        ? "Fix the first error and rebuild — later ones are often caused by it."
        : undefined,
      detail: kotlinErrors.slice(0, 8).map((m) => `${m[4]}\n  at ${m[1]}:${m[2]}`).join("\n"),
    });
  }

  const notFound = output.match(/Could not (?:find|resolve) ([^\s.]+:[^\s.]+:[^\s.]+)/);
  if (notFound) {
    return new ZetaError(`Dependency not found: ${notFound[1]}`, {
      hint: "Check the coordinate in [dependencies]. It must be group:artifact:version and exist on Maven Central or Google's repository.",
      docs: "dependencies.md",
    });
  }

  if (/Could not resolve all|UnknownHostException|Connection timed out/i.test(output)) {
    return new ZetaError("Could not download dependencies.", {
      hint: "The build needs the network the first time. If you are behind a proxy, set HTTP_PROXY / HTTPS_PROXY, then retry.",
      docs: "troubleshooting.md",
    });
  }

  return new ZetaError("The build failed.", {
    detail: output,
    hint: "Run with --verbose to see the full Gradle output.",
  });
}
